"use client";

// Cenniki dla poszczególnych kategorii
const businessClassPrices = [
  { city: "Athlone", price: "€240", link: "/booking?destination=Athlone" },
  { city: "Belfast", price: "€290", link: "/booking?destination=Belfast" },
  { city: "Clonmel", price: "€320", link: "/booking?destination=Clonmel" },
  { city: "Cliffs of Moher", price: "€420", link: "/booking?destination=Cliffs of Moher" },
  { city: "Clifden", price: "€400", link: "/booking?destination=Clifden" },
  { city: "Cork", price: "€390", link: "/booking?destination=Cork" },
  { city: "Derry", price: "€430", link: "/booking?destination=Derry" },
  { city: "Dingle", price: "€530", link: "/booking?destination=Dingle" },
  { city: "Doolin", price: "€420", link: "/booking?destination=Doolin" },
  { city: "Donegal", price: "€430", link: "/booking?destination=Donegal" },
  { city: "Galway", price: "€340", link: "/booking?destination=Galway" },
  { city: "Kilkenny", price: "€240", link: "/booking?destination=Kilkenny" },
  { city: "Killarney", price: "€450", link: "/booking?destination=Killarney" },
  { city: "Limerick", price: "€340", link: "/booking?destination=Limerick" },
  { city: "Sligo", price: "€350", link: "/booking?destination=Sligo" },
  { city: "Tipperary", price: "€320", link: "/booking?destination=Tipperary" },
  { city: "Tralee", price: "€440", link: "/booking?destination=Tralee" },
  { city: "Waterford", price: "€290", link: "/booking?destination=Waterford" },
  { city: "Westport", price: "€380", link: "/booking?destination=Westport" },
  { city: "Wexford", price: "€270", link: "/booking?destination=Wexford" },
];

const castleHotelsPrices = [
  { city: "Abbeyglen Castle", price: "€365", link: "/booking?destination=Abbeyglen Castle" },
  { city: "Adare Manor", price: "€365", link: "/booking?destination=Adare Manor" },
  { city: "Ashford Castle", price: "€395", link: "/booking?destination=Ashford Castle" },
  { city: "Ballygally Castle", price: "€345", link: "/booking?destination=Ballygally Castle" },
  { city: "Ballynahinch Castle", price: "€455", link: "/booking?destination=Ballynahinch Castle" },
  { city: "Ballyseede Castle", price: "€435", link: "/booking?destination=Ballyseede Castle" },
  { city: "Ballyfin Demesne", price: "€195", link: "/booking?destination=Ballyfin Demesne" },
  { city: "Cabra Castle", price: "€225", link: "/booking?destination=Cabra Castle" },
  { city: "Castle Leslie Estate", price: "€235", link: "/booking?destination=Castle Leslie Estate" },
  { city: "Castlemartyr Resort", price: "€445", link: "/booking?destination=Castlemartyr Resort" },
  { city: "Dromoland Castle", price: "€395", link: "/booking?destination=Dromoland Castle" },
  { city: "Glenlo Abbey Hotel", price: "€395", link: "/booking?destination=Glenlo Abbey Hotel" },
  { city: "Harvey's Point", price: "€415", link: "/booking?destination=Harvey's Point" },
  { city: "Kilkea Castle", price: "€145", link: "/booking?destination=Kilkea Castle" },
  { city: "Knockranny House", price: "€425", link: "/booking?destination=Knockranny House" },
  { city: "Lough Erne Resort", price: "€275", link: "/booking?destination=Lough Erne Resort" },
  { city: "Lough Eske Castle", price: "€395", link: "/booking?destination=Lough Eske Castle" },
  { city: "Lough Rynn Castle", price: "€275", link: "/booking?destination=Lough Rynn Castle" },
  { city: "Markree Castle", price: "€345", link: "/booking?destination=Markree Castle" },
  { city: "Mount Juliet Estate", price: "€275", link: "/booking?destination=Mount Juliet Estate" },
];

const mpvAndFirstClassPrices = [
  { city: "Athlone", price: "€310", link: "/booking?destination=Athlone" },
  { city: "Belfast", price: "€360", link: "/booking?destination=Belfast" },
  { city: "Clonmel", price: "€390", link: "/booking?destination=Clonmel" },
  { city: "Cliffs of Moher", price: "€490", link: "/booking?destination=Cliffs of Moher" },
  { city: "Clifden", price: "€470", link: "/booking?destination=Clifden" },
  { city: "Cork", price: "€460", link: "/booking?destination=Cork" },
  { city: "Derry", price: "€500", link: "/booking?destination=Derry" },
  { city: "Dingle", price: "€600", link: "/booking?destination=Dingle" },
  { city: "Doolin", price: "€490", link: "/booking?destination=Doolin" },
  { city: "Donegal", price: "€500", link: "/booking?destination=Donegal" },
  { city: "Galway", price: "€410", link: "/booking?destination=Galway" },
  { city: "Kilkenny", price: "€310", link: "/booking?destination=Kilkenny" },
  { city: "Killarney", price: "€520", link: "/booking?destination=Killarney" },
  { city: "Limerick", price: "€410", link: "/booking?destination=Limerick" },
  { city: "Sligo", price: "€420", link: "/booking?destination=Sligo" },
  { city: "Tipperary", price: "€390", link: "/booking?destination=Tipperary" },
  { city: "Tralee", price: "€520", link: "/booking?destination=Tralee" },
  { city: "Waterford", price: "€360", link: "/booking?destination=Waterford" },
  { city: "Westport", price: "€450", link: "/booking?destination=Westport" },
  { city: "Wexford", price: "€340", link: "/booking?destination=Wexford" },
];

const castleHotelsExtendedPrices = [
  { city: "Abbeyglen Castle", price: "€435", link: "/booking?destination=Abbeyglen Castle" },
  { city: "Adare Manor", price: "€435", link: "/booking?destination=Adare Manor" },
  { city: "Ashford Castle", price: "€465", link: "/booking?destination=Ashford Castle" },
  { city: "Ballygally Castle", price: "€405", link: "/booking?destination=Ballygally Castle" },
  { city: "Ballynahinch Castle", price: "€515", link: "/booking?destination=Ballynahinch Castle" },
  { city: "Ballyseede Castle", price: "€535", link: "/booking?destination=Ballyseede Castle" },
  { city: "Ballyfin Demesne", price: "€255", link: "/booking?destination=Ballyfin Demesne" },
  { city: "Cabra Castle", price: "€285", link: "/booking?destination=Cabra Castle" },
  { city: "Castle Leslie Estate", price: "€295", link: "/booking?destination=Castle Leslie Estate" },
  { city: "Castlemartyr Resort", price: "€515", link: "/booking?destination=Castlemartyr Resort" },
  { city: "Dromoland Castle", price: "€455", link: "/booking?destination=Dromoland Castle" },
  { city: "Glenlo Abbey Hotel", price: "€455", link: "/booking?destination=Glenlo Abbey Hotel" },
  { city: "Harvey’s Point", price: "€475", link: "/booking?destination=Harvey’s Point" },
  { city: "Kilkea Castle", price: "€205", link: "/booking?destination=Kilkea Castle" },
  { city: "Knockranny House", price: "€495", link: "/booking?destination=Knockranny House" },
  { city: "Lough Erne Resort", price: "€335", link: "/booking?destination=Lough Erne Resort" },
  { city: "Lough Eske Castle", price: "€455", link: "/booking?destination=Lough Eske Castle" },
  { city: "Lough Rynn Castle", price: "€335", link: "/booking?destination=Lough Rynn Castle" },
  { city: "Markree Castle", price: "€405", link: "/booking?destination=Markree Castle" },
  { city: "Mount Juliet Estate", price: "€335", link: "/booking?destination=Mount Juliet Estate" },
];

const golfResortTransfersPrices = [
  { city: "Royal County Down (Championship Course)", price: "€370", link: "/booking?destination=Royal County Down" },
  { city: "Royal Portrush (Dunluce Links)", price: "€500", link: "/booking?destination=Royal Portrush" },
  { city: "Ballybunion Golf Club", price: "€580", link: "/booking?destination=Ballybunion Golf Club" },
  { city: "Lahinch Golf Club", price: "€540", link: "/booking?destination=Lahinch Golf Club" },
  { city: "Rosapenna Golf Resort, St Patrick's Links", price: "€600", link: "/booking?destination=Rosapenna Golf Resort" },
  { city: "Waterville Golf Links", price: "€680", link: "/booking?destination=Waterville Golf Links" },
  { city: "The Golf Course at Adare Manor", price: "€440", link: "/booking?destination=The Golf Course at Adare Manor" },
  { city: "Tralee Golf Club", price: "€630", link: "/booking?destination=Tralee Golf Club" },
  { city: "The County Sligo Golf Club", price: "€520", link: "/booking?destination=The County Sligo Golf Club" },
  { city: "Trump International Golf Links & Hotel Doonbeg Ireland", price: "€520", link: "/booking?destination=Trump International Golf Links" },
  { city: "Mount Juliet Estate, Autograph Collection", price: "€350", link: "/booking?destination=Mount Juliet Estate" },
  { city: "Old Head Golf Links", price: "€580", link: "/booking?destination=Old Head Golf Links" },
];

export {
  businessClassPrices,
  castleHotelsPrices,
  mpvAndFirstClassPrices,
  castleHotelsExtendedPrices,
  golfResortTransfersPrices
};